apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnailer-deployment
  namespace: smanzy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thumbnailer
  template:
    metadata:
      labels:
        app: thumbnailer
    spec:
      containers:
      - name: thumbnailer
        image: ghcr.io/vozigo/smanzary-thumbnailer:latest
        imagePullPolicy: Always
        command: ["./thumbgen"]
        env:
        - name: UPLOAD_DIR
          valueFrom:
            configMapKeyRef:
              name: smanzy-config
              key: UPLOAD_DIR_THUMBGEN
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/uploads
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: uploads-pvc